### PR TITLE
Update first homework

### PR DESCRIPTION
**Pull request by francois-rozet**

### CODE REVIEW

**Comment by glouppe** [comment]
Prochaine fois laisse nous le temps de reviewer quand meme :)

**Comment by glouppe** [comment]
In Section 2.2., it should be `.zero_()` instead of `.zero()` to reset the gradient values.

**Comment by glouppe** [comment]
Fortunatly -> Fortunately

**Comment by francois-rozet** [comment]
Merged by accident. New PR #21 .

**Pull request merged**
