### PR TITLE
PyTorch tutorial

### PR DESCRIPTION
**Pull request by JoeriHermans**
Practical session covering PyTorch.

**Do not merge yet**

### CODE REVIEW

**Comment by JoeriHermans** [comment]
Ping @glouppe 

Any comments? Just need to add the associated Markdown text.

**Comment by glouppe** [comment]
Thanks a lot! This looks very nice.

**Comment by glouppe** [comment]
Ping me when you want this to be merged.

**Comment by JoeriHermans** [comment]
Ping @glouppe 

Ready!

**Pull request merged**
